name: Simpleplayertracker
version: '${project.version}'
main: me.jordan.simpleplayertracker.Main
api-version: 1.20
authors: [ BlackScorpyon04 ]
description: Tracks players using a compass

commands:
  ptcompass:
    description: Gives player a compass